### ISSUE TITLE
Nothing return

### ISSUE THREAD

**Issue by callmejm** [Bujupah/dart_ipify#5]
final ipv4 = await Ipify.ipv4();

Try to get the IP, but nothing return

**Comment by callmejm** [comment]
I think ipify server down

**Comment by callmejm** [comment]
Not server down, my wifi can't get , if I change to data or vpn no problem

**Comment by callmejm** [comment]
Unhandled Exception: Exception: The request failed because it wasn't able to reach the ipify service. This is most likely due to a networking error of some sort.

**Comment by Bujupah** [comment]
Is there a defect in the package or the ipify server is down or your net is messing up with ya 😋 ? I am confused 🤔

**Comment by callmejm** [comment]
@Bujupah not ipify server down, my net is fine, dio call other api is no problem, but when I try t get ipv4, I dont receive any value, then I try browse ipify website in my pc, also can't enter

**Comment by Bujupah** [comment]
@callmejm Seems like firewall issue

**Comment by callmejm** [comment]
> @callmejm Seems like firewall issue

How to resolve

**Comment by shiburagi** [comment]
I faced this issue too

**Comment by Bujupah** [comment]
@callmejm @shiburagi 
I couldn't produce on my machines
I am pretty sure this is a firewall issue, or else ipify is blacklisting your ip

**Comment by Bujupah** [comment]
closing this cause of inactivity
